### ISSUE TITLE
Crash on Final Chapter Story Mode

### ISSUE THREAD

**Issue by JBLeopard** [Rinnegatamante/mcpixel-vita#1]
Hello, the game crashes in the last stage of round 4-B, I have tried to change the language and the screen resolution but it continues to give the same result, with this problem you cannot go to round 4-C so far everything works perfect, thank you for this great port!, the used version of the android apk is 1.1.4.
![2023-08-15-181319](https://github.com/Rinnegatamante/mcpixel-vita/assets/68962385/5172cff5-c311-4793-a513-002852bbb2e9)

**Comment by Rinnegatamante** [comment]
Can you share a save file?

**Comment by JBLeopard** [comment]
Yes, of course, the savedata files of this game are "backup.json" , "progress.json" and "settings.json"... Its ok?
[save.zip](https://github.com/Rinnegatamante/mcpixel-vita/files/12346995/save.zip)

**Comment by Rinnegatamante** [comment]
Steps to reproduce the crash from the save?

**Comment by JBLeopard** [comment]
> Steps to reproduce the crash from the save?

Hello, you have to go to History menu, and then to Final Chapter {Chapter 4), load Round 4-B.

**Comment by JBLeopard** [comment]
> Steps to reproduce the crash from the save?
Last night I did all the other stages, dlcs, extras and secrets at 100% to do further testing and see if it suffered any crashes at another point, nothing strange, everything else works fine.

**Comment by Rinnegatamante** [comment]
[mcpixel.zip](https://github.com/Rinnegatamante/mcpixel-vita/files/12357884/mcpixel.zip)

Check if the crash happens with this build.

**Comment by JBLeopard** [comment]
> [mcpixel.zip](https://github.com/Rinnegatamante/mcpixel-vita/files/12357884/mcpixel.zip)
> 
> Check if the crash happens with this build.

Now if it loads correctly, I'll finish it completely and I'll tell you the result, thank you very much.

**Comment by JBLeopard** [comment]
Fully tested and fully playable, 100% of the game, thanks.
